name: Development Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/unit-tests.yml
    with:
      ios-version: '17.2'
      macos-runner: 'macos-14'
      
  pre-merge-tests:
    uses: ./.github/workflows/unit-tests.yml
    with:
      ios-version: '16.1'
      macos-runner: 'macos-13-xlarge'
      environment: 'pre-release'
